# Generated by Django 5.0.3 on 2024-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.FloatField()),
                ('score', models.IntegerField()),
                ('grade', models.CharField(max_length=1)),
                ('row_number', models.IntegerField()),
            ],
        ),
    ]
