# Generated by Django 5.0.3 on 2024-03-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APiApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='birthdate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='grade',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='row_number',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
